#!/bin/bash
#PBS -N train_hair
#PBS -l select=1:ncpus=8:mem=64gb:ngpus=1
#PBS -l walltime=24:00:00
#PBS -j oe
#PBS -o /scratch/users/ntu/song0304/loraedit_exp/logs/train_hair.log
#PBS -P personal-song0304
#PBS -q normal

cd /home/users/ntu/song0304/code/LoRAEdit
source activate loraedit

mkdir -p /scratch/users/ntu/song0304/loraedit_exp/logs

NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" \
deepspeed --num_gpus=1 train.py \
  --deepspeed \
  --config /scratch/users/ntu/song0304/loraedit_exp/processed_data/V7_hair/configs/training.toml

echo "Training done at $(date)"
